[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/webgl/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/play/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
